import { test, expect, type Page } from '@playwright/test'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../story-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeAll(async () => { server = await startEditorServer(['--patch', resolve('plugins/writer-sessions/e2e/fixture.patch.yml')]) })
test.afterAll(async () => { await server?.stop() })
async function call(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  expect(response.status()).toBe(200)
  const result = (await response.json()).result
  expect(result.ok, JSON.stringify(result)).toBe(true)
  return result.value
}
test('frozen opening appears before a model request and survives reload, Fork and source deletion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) })
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'Performance project' })
  const script = await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Frozen opening', defaultLanguage: 'en' })
  await call(page, 'papermoon/save', { scriptId: script.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'story.js', source: 'module.exports={systemPrompt:"Exact {{literal}} system.",messages:[{name:"Opening",role:"assistant",content:"Assistant fixture text."},{name:"Background",role:"user",content:"Background fixture text."},{role:"user",content:""}]}' }] })
  const revision = await call(page, 'papermoon/commit', { scriptId: script.id, expectedSequence: 1, description: 'First playable revision' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + script.id, server.url).href)
  await expect(page.getByRole('button', { name: 'Start performance', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Compile', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('First playable revision')
  await expect(dialog.getByRole('button', { name: 'Model', exact: true })).toContainText('Fixture model')
  await dialog.getByRole('button', { name: 'Start performance', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.ppm-authored').first()).toContainText('Assistant fixture text.')
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  expect(existsSync(join(server.directory, 'data/requests.jsonl'))).toBe(false)
  const initialList = await call(page, 'session/list', { args: { _request: {} } })
  expect(initialList.items.filter((item: { blank: boolean }) => !item.blank)).toHaveLength(1)
  const found = await call(page, 'session/search', { args: { request: { query: 'Background fixture' } } })
  expect(found.items).toHaveLength(1)
  await page.reload()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await input.fill('User fixture input.'); await input.press('Enter')
  await expect(page.locator('p').filter({ hasText: /^Fixture reply\.$/ })).toBeVisible()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const requests = () => readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  expect(requests()).toHaveLength(1)
  expect(requests()[0].messages.map((m: { role: string }) => m.role)).toEqual(['system', 'assistant', 'user', 'user', 'user'])
  expect(requests()[0].messages.map((m: { content: { text: string }[] }) => m.content.map(b => b.text).join(''))).toEqual(['Exact {{literal}} system.', 'Assistant fixture text.', 'Background fixture text.', '', 'User fixture input.'])
  expect(requests()[0].tools ?? []).toEqual([])
  await page.screenshot({ path: 'test-results/papermoon-performance.png', fullPage: true })
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByText('Assistant fixture text.', { exact: true }).first()).toBeVisible()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  const state = await call(page, 'session/list', { args: { _request: {} } })
  const sessionId = state.items.find((item: { agentPreset?: string }) => item.agentPreset === 'papermoon-moderator')?.sessionId ?? state.items[0].sessionId
  const child = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: child.sessionId })).fixed.revisionId).toBe(revision.revision.id)
  await call(page, 'papermoon/deleteScript', { scriptId: script.id })
  const afterDeletion = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: afterDeletion.sessionId })).sourceMissing).toBe(true)
  await call(page, 'session/prompt', { args: { request: { sessionId: child.sessionId, historyVersion: (await call(page, 'papermoon-performances/state', { sessionId: child.sessionId })).worldline.version, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: 'Continue' }] } } })
  await expect.poll(() => requests().length).toBe(2)
  expect(requests()[1].messages.filter((m: { content: { text: string }[] }) => m.content.some(b => b.text === 'Assistant fixture text.'))).toHaveLength(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('previews functions and inspects committed state through the native tool conversation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'Functions project' })
  const script = await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Counter', defaultLanguage: 'en' })
  const source = `function factory({state}) {
/** Increase the count.
 * @param {number} amount Amount.
 * @returns {number|{value:number}} Updated count.
 */
return function increment(amount) { state.count += amount; return state.count; }
}
module.exports={systemPrompt:'Function fixture.',messages:[],state:{initial:{count:0},schema:{type:'object',properties:{count:{type:'number'}},required:['count'],additionalProperties:false}},functions:[factory]};`
  await call(page, 'papermoon/save', { scriptId: script.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'story.js', source }] })
  const revision = await call(page, 'papermoon/commit', { scriptId: script.id, expectedSequence: 1, description: 'Function revision' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + script.id, server.url).href)
  await page.getByText('Functions · 1', { exact: true }).click()
  await page.getByText('increment', { exact: true }).click()
  await expect(page.getByText('Increase the count.', { exact: true })).toBeVisible()
  await page.getByText('Initial state', { exact: true }).click()
  await expect(page.locator('pre').filter({ hasText: '"count": 0' })).toBeVisible()
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Start performance', exact: true }).click()
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await expect(input).toHaveAttribute('contenteditable', 'true')
  await input.fill('Call the function.')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await input.press('Enter')
  await expect(page.locator('p').filter({ hasText: /^Fixture reply\.$/ })).toBeVisible()
  const requests = readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  await expect(page.getByText('Fixture intermediate reply.', { exact: true })).toBeVisible()
  await expect(page.getByText('Fixture intermediate reasoning.', { exact: true })).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('Fixture intermediate reply.', { exact: true })).toBeVisible()
  await expect(page.getByText('Fixture intermediate reasoning.', { exact: true })).not.toBeVisible()
  const results = requests.at(-1).messages.flatMap((message: { content: unknown[] }) => message.content).filter((block: { type: string }) => block.type === 'tool-result')
  expect(results.map((block: {content: unknown}) => block.content)).toEqual([[{type:'text',text:'3'}]])
  await page.locator('.ppm-source > summary').click()
  await page.getByText('Current state', { exact: true }).click()
  await expect(page.locator('.ppm-inspection pre').first()).toContainText('"count": 3')
  await page.getByText('Action records · 1', { exact: true }).click()
  await page.locator('.ppm-inspection summary').filter({ hasText: /increment/ }).click()
  await expect(page.locator('.ppm-inspection pre').last()).toContainText('"value": 3')
  await expect(page.locator('.ppm-source > div')).toHaveCSS('border-top-width', '1px')
  await page.screenshot({ path: 'test-results/papermoon-functions.png', fullPage: true })
  await page.reload()
  await page.locator('.ppm-source > summary').click()
  await page.getByText('Current state', { exact: true }).click()
  await expect(page.locator('.ppm-inspection pre').first()).toContainText('"count": 3')
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByText('increment', { exact: true }).first()).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.ppm-source > summary').click()
  await expect(page.locator('.ppm-inspection')).toBeVisible()
  const bounds = await page.locator('.ppm-source > div').boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-results/papermoon-functions-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})


test('switches immutable worldlines without mixing chat history or losing the unsent draft', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'History fixture' })
  const script = await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Worldlines fixture', defaultLanguage: 'en' })
  await call(page, 'papermoon/save', { scriptId: script.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'story.js', source: 'module.exports={systemPrompt:"History fixture.",messages:[]}' }] })
  const revision = await call(page, 'papermoon/commit', { scriptId: script.id, expectedSequence: 1, description: 'Worldline fixture' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + script.id, server.url).href)
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Start performance', exact: true }).click()
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  const send = async (text: string, count: number) => {
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(input).toHaveAttribute('contenteditable', 'true')
    await input.fill(text); await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled(); await input.press('Enter')
    await expect(page.getByRole('button', { name: 'Reroll', exact: true })).toHaveCount(count)
  }
  await send('First turn', 1)
  await send('Second turn', 2)
  await page.getByRole('button', { name: 'Continue from here', exact: true }).first().click()
  await expect(page.getByText('Second turn', { exact: true })).toHaveCount(0)
  await send('Alternate turn', 2)
  await page.getByRole('tab', { name: 'Worldlines', exact: true }).click()
  await expect(page.locator('.ppm-world-graph li')).toHaveCount(4)
  const second = page.locator('.ppm-world-graph li > button').nth(2)
  await second.click()
  await expect(page.locator('.ppm-world-detail')).toContainText('Second turn')
  await expect(page.locator('.ppm-world-graph [aria-current="true"]')).toContainText('Alternate turn')
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  await input.fill('Keep this draft')
  await page.getByRole('button', { name: 'Reroll', exact: true }).last().click()
  await expect(input).toHaveText('Keep this draft')
  await expect(page.getByRole('button', { name: 'Reroll', exact: true }).last()).toBeEnabled()
  await expect(page.locator('[data-chat-flow-kind="user"]').filter({ hasText: 'Alternate turn' })).toHaveCount(1)
  await page.getByRole('tab', { name: 'Worldlines', exact: true }).click()
  await expect(page.locator('.ppm-world-graph li')).toHaveCount(5)
  const siblingEdges = page.locator('[data-world-edge]')
  const edges = await siblingEdges.evaluateAll(paths => paths.map(path => ({ parent: path.getAttribute('data-parent-node'), lane: path.getAttribute('data-lane'), path: path.getAttribute('d') })))
  expect(edges[2]!.parent).toBe(edges[3]!.parent)
  expect(edges[2]!.lane).not.toBe(edges[3]!.lane)
  expect(edges[3]!.path).toContain(' C ')
  await page.locator('.ppm-world-graph li > button').nth(4).click()
  const detail = page.locator('.ppm-world-detail')
  await expect(page.getByRole('button', { name: 'Reroll', exact: true })).toHaveCount(0)
  const operations: string[] = []
  page.on('request', request => { if (request.url().endsWith('/api/papermoon-performances/operation')) operations.push(request.url()) })
  const browseCandidate = async (ordinal: number, current: number) => {
    const before = operations.length
    await detail.getByRole('button', { name: 'Historical results', exact: true }).click()
    await page.getByRole('menuitem', { name: '#' + ordinal + ' · Completed', exact: true }).click()
    await expect(page.locator('.ppm-world-graph .ppm-inspected .ppm-world-node-head b')).toHaveText('#' + ordinal)
    await expect(detail.getByRole('heading', { level: 3 })).toHaveText('Node #' + ordinal)
    await expect(detail.getByRole('button', { name: 'Historical results', exact: true })).toContainText('#' + ordinal)
    await expect(page.locator('.ppm-world-graph [aria-current="true"] .ppm-world-node-head b')).toHaveText('#' + current)
    expect(operations).toHaveLength(before)
  }
  const switchHere = async (ordinal: number) => {
    const before = operations.length
    await detail.getByRole('button', { name: 'Switch to here', exact: true }).click()
    await expect(page.locator('.ppm-world-graph [aria-current="true"] .ppm-world-node-head b')).toHaveText('#' + ordinal)
    await expect(detail.getByRole('button', { name: 'Switch to here', exact: true })).toBeDisabled()
    expect(operations).toHaveLength(before + 1)
  }
  await browseCandidate(3, 4)
  await switchHere(3)
  await browseCandidate(4, 3)
  await switchHere(4)
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Rewind', exact: true })).toHaveCount(0)
  await page.locator('[data-chat-flow-kind="user"]').filter({ hasText: 'First turn' }).getByRole('button', { name: 'Edit message', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('The original message and reply stay in history')
  await page.getByRole('dialog').getByRole('textbox', { name: 'Message text' }).fill('Edited first turn')
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(input).toHaveText('Keep this draft')
  await expect(page.getByText('First turn', { exact: true })).toBeVisible()
  await page.locator('[data-chat-flow-kind="user"]').filter({ hasText: 'First turn' }).getByRole('button', { name: 'Edit message', exact: true }).click()
  await page.getByRole('dialog').getByRole('textbox', { name: 'Message text' }).fill('Edited first turn')
  await page.getByRole('dialog').getByRole('button', { name: 'Submit and regenerate', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(input).toHaveText('Keep this draft')
  await expect(page.getByRole('button', { name: 'Reroll', exact: true })).toHaveCount(1)
  await expect(page.locator('[data-chat-flow-kind="user"]').filter({ hasText: 'Edited first turn' })).toHaveCount(1)
  await expect(page.getByText('First turn', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.locator('[data-chat-flow-kind="user"]').filter({ hasText: 'Edited first turn' })).toHaveCount(1)
  await page.getByRole('tab', { name: 'Worldlines', exact: true }).click()
  await expect(page.locator('.ppm-world-graph li')).toHaveCount(6)
  const treeList = page.locator('.ppm-world-list')
  for (let i = 0; i < 2; i++) {
    await treeList.evaluate(element => { element.style.maxHeight = '120px'; element.scrollTop = element.scrollHeight })
    await page.getByRole('button', { name: 'Locate current', exact: true }).click()
    await expect.poll(() => treeList.evaluate(element => {
      const current = element.querySelector('[aria-current="true"]')!.getBoundingClientRect(), bounds = element.getBoundingClientRect()
      return current.top >= bounds.top && current.bottom <= bounds.bottom
    })).toBe(true)
  }
  await treeList.evaluate(element => { element.style.maxHeight = '' })
  await browseCandidate(1, 5)
  await switchHere(1)
  await browseCandidate(5, 1)
  await page.locator('.ppm-world-graph li > button').first().focus()
  await page.keyboard.press('ArrowDown')
  await expect(page.locator('.ppm-world-graph li > button').nth(1)).toBeFocused()
  await page.getByRole('heading', { name: 'Worldlines', exact: true }).click()
  await page.screenshot({ path: 'test-results/papermoon-worldlines.png', fullPage: true })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ path: 'test-results/papermoon-worldlines-dark.png', fullPage: true })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect.poll(async () => (await page.locator('.ppm-world').boundingBox())!.width).toBeGreaterThan(300)
  await detail.getByRole('heading', { level: 3 }).scrollIntoViewIfNeeded()
  await expect(detail.getByRole('button', { name: 'Switch to here', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/papermoon-worldlines-narrow.png', fullPage: true })
  const stateDetails = detail.locator('.ppm-world-disclosure').first()
  await stateDetails.locator('summary').focus()
  await page.keyboard.press('Enter')
  await expect(stateDetails).toHaveAttribute('open', '')
  expect(errors).toEqual([])
})
