import { test, expect, type Page } from '@playwright/test'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../playbook-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeAll(async () => { server = await startEditorServer(['--patch', resolve('plugins/writer-sessions/e2e/fixture.patch.yml')]) })
test.afterAll(async () => { await server?.stop() })
async function call(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  expect(response.status()).toBe(200)
  const result = (await response.json()).result
  expect(result.ok, JSON.stringify(result)).toBe(true)
  return result.value
}
test('frozen opening appears before a model request and survives reload, Fork and source deletion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) })
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'Performance project' })
  const playbook = await call(page, 'papermoon/createPlaybook', { projectId: project.id, name: 'Frozen opening', defaultLanguage: 'en' })
  await call(page, 'papermoon/save', { playbookId: playbook.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'playbook.js', source: 'module.exports={systemPrompt:"Exact {{literal}} system.",messages:[{name:"Opening",role:"assistant",content:"Assistant fixture text."},{name:"Background",role:"user",content:"Background fixture text."},{role:"user",content:""}]}' }] })
  const revision = await call(page, 'papermoon/commit', { playbookId: playbook.id, expectedSequence: 1, description: 'First playable revision' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + playbook.id, server.url).href)
  await expect(page.getByRole('button', { name: 'Start performance', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Compile', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('First playable revision')
  await expect(dialog.getByRole('button', { name: 'Model', exact: true })).toContainText('Fixture model')
  await dialog.getByRole('button', { name: 'Start performance', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.ppm-authored').first()).toContainText('Assistant fixture text.')
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  expect(existsSync(join(server.directory, 'data/requests.jsonl'))).toBe(false)
  const initialList = await call(page, 'session/list', { args: { _request: {} } })
  expect(initialList.items.filter((item: { blank: boolean }) => !item.blank)).toHaveLength(1)
  const found = await call(page, 'session/search', { args: { request: { query: 'Background fixture' } } })
  expect(found.items).toHaveLength(1)
  await page.reload()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await input.fill('User fixture input.'); await input.press('Enter')
  await expect(page.locator('p').filter({ hasText: /^Fixture reply\.$/ })).toBeVisible()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const requests = () => readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  expect(requests()).toHaveLength(1)
  expect(requests()[0].messages.map((m: { role: string }) => m.role)).toEqual(['system', 'assistant', 'user', 'user', 'user'])
  expect(requests()[0].messages.map((m: { content: { text: string }[] }) => m.content.map(b => b.text).join(''))).toEqual(['Exact {{literal}} system.', 'Assistant fixture text.', 'Background fixture text.', '', 'User fixture input.'])
  expect(requests()[0].tools ?? []).toEqual([])
  await page.screenshot({ path: 'test-results/papermoon-performance.png', fullPage: true })
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByRole('row').filter({hasText:'Assistant fixture text.'}).first()).toBeVisible()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  const state = await call(page, 'session/list', { args: { _request: {} } })
  const sessionId = state.items.find((item: { agentPreset?: string }) => item.agentPreset === 'papermoon-moderator')?.sessionId ?? state.items[0].sessionId
  const child = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: child.sessionId })).fixed.revisionId).toBe(revision.revision.id)
  await call(page, 'papermoon/deletePlaybook', { playbookId: playbook.id })
  const afterDeletion = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: afterDeletion.sessionId })).sourceMissing).toBe(true)
  await call(page, 'session/prompt', { args: { request: { sessionId: child.sessionId, historyVersion: (await call(page, 'papermoon-performances/state', { sessionId: child.sessionId })).worldline.version, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: 'Continue' }] } } })
  await expect.poll(() => requests().length).toBe(2)
  expect(requests()[1].messages.filter((m: { content: { text: string }[] }) => m.content.some(b => b.text === 'Assistant fixture text.'))).toHaveLength(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('previews functions and inspects committed state through the native tool conversation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'Functions project' })
  const playbook = await call(page, 'papermoon/createPlaybook', { projectId: project.id, name: 'Counter', defaultLanguage: 'en' })
  const source = `function factory({state}) {
/** Increase the count.
 * @param {number} amount Amount.
 * @returns {number|{value:number}} Updated count.
 */
return function increment(amount) { state.count += amount; return state.count; }
}
module.exports={systemPrompt:'Function fixture.',messages:[],state:{initial:{count:0},schema:{type:'object',properties:{count:{type:'number'}},required:['count'],additionalProperties:false}},functions:[factory]};`
  await call(page, 'papermoon/save', { playbookId: playbook.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'playbook.js', source }] })
  const revision = await call(page, 'papermoon/commit', { playbookId: playbook.id, expectedSequence: 1, description: 'Function revision' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + playbook.id, server.url).href)
  await page.getByText('Functions · 1', { exact: true }).click()
  await page.getByText('increment', { exact: true }).click()
  await expect(page.getByText('Increase the count.', { exact: true })).toBeVisible()
  await page.getByText('Initial state', { exact: true }).click()
  await expect(page.locator('pre').filter({ hasText: '"count": 0' })).toBeVisible()
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Start performance', exact: true }).click()
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await expect(input).toHaveAttribute('contenteditable', 'true')
  await input.fill('Call the function.')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await input.press('Enter')
  await expect(page.locator('p').filter({ hasText: /^Fixture reply\.$/ })).toBeVisible()
  const requests = readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  await expect(page.getByText('Fixture intermediate reply.', { exact: true })).toBeVisible()
  await expect(page.getByText('Fixture intermediate reasoning.', { exact: true })).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('Fixture intermediate reply.', { exact: true })).toBeVisible()
  await expect(page.getByText('Fixture intermediate reasoning.', { exact: true })).not.toBeVisible()
  const results = requests.at(-1).messages.filter((message: { role: string }) => message.role === 'tool')
  expect(results.map((block: {content: unknown}) => block.content)).toEqual([[{type:'text',text:'3'}]])
  await page.locator('.ppm-source > summary').click()
  await page.getByText('Current state', { exact: true }).click()
  await expect(page.locator('.ppm-inspection pre').first()).toContainText('"count": 3')
  await page.getByText('Action records · 1', { exact: true }).click()
  await page.locator('.ppm-inspection summary').filter({ hasText: /increment/ }).click()
  await expect(page.locator('.ppm-inspection pre').last()).toContainText('"value": 3')
  await expect(page.locator('.ppm-source > div')).toHaveCSS('border-top-width', '1px')
  await page.screenshot({ path: 'test-results/papermoon-functions.png', fullPage: true })
  await page.reload()
  await page.locator('.ppm-source > summary').click()
  await page.getByText('Current state', { exact: true }).click()
  await expect(page.locator('.ppm-inspection pre').first()).toContainText('"count": 3')
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByText('increment', { exact: true }).first()).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('.ppm-source > summary').click()
  await expect(page.locator('.ppm-inspection')).toBeVisible()
  const bounds = await page.locator('.ppm-source > div').boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'test-results/papermoon-functions-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})


test('inspects worldlines in the full trajectory without changing execution position', async ({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(String(e)))
  await page.addLocatorHandler(page.getByRole('button',{name:'Continue',exact:true}),async()=>{await page.getByRole('button',{name:'Continue',exact:true}).click()})
  await page.goto(server.url)
  const project=await call(page,'papermoon/createProject',{name:'Inspection project'})
  const playbook=await call(page,'papermoon/createPlaybook',{projectId:project.id,name:'Inspection playbook',defaultLanguage:'en'})
  const source=`module.exports={systemPrompt:'Context head',messages:[{role:'assistant',name:'Opening',content:'Frozen opening'}],composeContext({opening,input,history}){return {systemPrompt:opening.systemPrompt,messages:[...opening.messages.map(m=>({ref:m.id})),...history.slice().reverse().flatMap(n=>n.blocks.map(b=>({ref:b.id}))),{ref:input.id},{name:'Tail',role:'assistant',content:'Context tail '+history.length}]}}};`
  await call(page,'papermoon/save',{playbookId:playbook.id,expectedSequence:0,operations:[{kind:'create-file',path:'playbook.js',source}]})
  await call(page,'papermoon/commit',{playbookId:playbook.id,expectedSequence:1,description:'Inspection'})
  await page.goto(new URL('/#papermoon/'+playbook.id,server.url).href)
  await page.getByRole('button',{name:'Start performance',exact:true}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Start performance',exact:true}).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const input=page.getByRole('textbox').filter({visible:true}).last()
  const send=async(text:string,count:number)=>{await expect(input).toHaveAttribute('contenteditable','true');await input.fill(text);await expect(page.getByRole('button',{name:'Send message',exact:true})).toBeEnabled();await input.press('Enter');await expect(page.getByRole('button',{name:'Reroll',exact:true})).toHaveCount(count)}
  const expectInputBeforeThought = async (turn: number, text: string) => {
    const user = page.locator(`[data-chat-turn="${turn}"][data-chat-flow-kind="user"]`)
    await expect(user).toContainText(text)
    const thought = page.locator(`[data-chat-turn="${turn}"][data-chat-flow-kind="turn-process"]`).getByRole('button')
    await expect(thought).toBeVisible()
    const userBounds = await user.boundingBox(), thoughtBounds = await thought.boundingBox()
    expect(thoughtBounds!.y).toBeGreaterThanOrEqual(userBounds!.y + userBounds!.height)
  }
  await send('First input',1);await send('Second input',2);await send('Third input',3)
  await expectInputBeforeThought(3, 'Third input')
  await expect(page.locator('.ppm-context-entry')).toHaveCount(0)
  await expect(page.getByText('Context tail 2', {exact:true})).toHaveCount(0)
  await page.getByRole('tab',{name:'Trajectory',exact:true}).click()
  await expect(page.getByRole('tab',{name:'Worldlines',exact:true})).toHaveCount(0)
  await expect(page.getByRole('tab',{name:'Actual context',exact:true})).toHaveCount(0)
  const nav=page.locator('.ppm-navigation'),nodes=nav.locator('li>button'),toolbar=page.locator('.ppm-inspection-toolbar')
  await expect(nodes).toHaveCount(4)
  await expect(toolbar.getByRole('button',{name:'Rewritten context',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByRole('row').filter({hasText:'Context tail 2'}).first()).toBeVisible()
  const ordered = await page.getByRole('row').allTextContents()
  expect(ordered.findIndex(text=>text.includes('Second input'))).toBeLessThan(ordered.findIndex(text=>text.includes('First input')))
  await page.getByRole('row').filter({hasText:'Second input'}).first().click()
  await page.getByRole('button',{name:/History reference.*Floor 2/}).click()
  await expect(toolbar).toContainText('Floor 2')
  await expect(nav.locator('[aria-current="true"]')).toContainText('Third input')
  // The earlier request is inspected as one complete turn, rather than a request list page.
  await nodes.nth(1).click()
  await expect(toolbar).toContainText('Floor 1')
  await expect(nav.locator('[aria-current="true"]')).toContainText('Third input')
  await expect(page.getByRole('row').filter({hasText:'Context tail 0'}).first()).toBeVisible()
  await expect(page.getByRole('button',{name:'Reroll',exact:true})).toHaveCount(0)
  await toolbar.getByRole('button',{name:'Original context',exact:true}).click()
  await expect(page.getByRole('row').filter({hasText:'First input'}).last()).toBeVisible()
  await expect(page.getByText('Third input',{exact:true})).toHaveCount(1) // navigation only
  await nodes.nth(2).click()
  await expect(toolbar.getByRole('button',{name:'Original context',exact:true})).toHaveAttribute('aria-pressed','true')
  for (const text of ['First input','Second input']) await expect(page.getByRole('row').filter({hasText:text}).last().locator('[data-role-kind]')).toHaveAttribute('data-role-kind','user')
  const dimensions = () => nodes.nth(2).locator('.ppm-node-summary').evaluate(element => ({height:element.getBoundingClientRect().height,lineHeight:parseFloat(getComputedStyle(element).lineHeight),scrollHeight:element.scrollHeight}))
  const selectedSize = await dimensions()
  await nodes.nth(1).click()
  expect(await dimensions()).toEqual(selectedSize)
  expect(selectedSize.height).toBeGreaterThanOrEqual(selectedSize.lineHeight)
  expect(selectedSize.scrollHeight).toBeLessThanOrEqual(selectedSize.height)
  await nodes.nth(2).click()
  await toolbar.getByRole('button',{name:'Switch to here',exact:true}).click()
  await expect(nav.locator('[aria-current="true"]')).toContainText('Second input')
  await page.getByRole('tab',{name:'Chat',exact:true}).click()
  await expect(page.locator('[data-chat-flow-kind="user"]').filter({hasText:'Third input'})).toHaveCount(0)
  await input.fill('Unsent input')
  await page.getByRole('button',{name:'Reroll',exact:true}).last().click()
  await expect(input).toHaveText('Unsent input')
  await expect(page.getByRole('button',{name:'Reroll',exact:true})).toHaveCount(2)
  await expectInputBeforeThought(4, 'Second input')
  const recorded = readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  const sameInput = recorded.filter(request => request.messages.some((message: { source: { kind: string }; content: { text?: string }[] }) => message.source.kind === 'user' && message.content.some(part => part.text === 'Second input')))
  const fresh = sameInput.at(-1).messages.filter((message: { source: { kind: string }; content: { text?: string }[] }) => message.source.kind === 'user' && message.content.some(part => part.text === 'Second input')).at(-1)
  expect(fresh.source.kind).toBe('user')
  expect(fresh.source.rpcId).toBeTruthy()
  expect(fresh.source.producer).toBeUndefined()
  expect(sameInput.at(-1).messages.map(({role,content}: {role:string;content:unknown})=>({role,content}))).toEqual(sameInput[0].messages.map(({role,content}: {role:string;content:unknown})=>({role,content})))
  const results = page.getByRole('button', {name:'Historical results', exact:true})
  await expect(results).toHaveText('2/2')
  await expect(page.getByRole('button', {name:'Next result', exact:true})).toBeDisabled()
  await results.click()
  await expect(page.getByRole('menuitem')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await expect(results).toBeFocused()
  await page.screenshot({path:'test-results/papermoon-chat-actions.png',fullPage:true})
  await page.getByRole('button', {name:'Previous result', exact:true}).click()
  await expect(results).toHaveText('1/2')
  await page.getByRole('button', {name:'Next result', exact:true}).click()
  await expect(results).toHaveText('2/2')
  await expectInputBeforeThought(4, 'Second input')
  await page.reload()
  await expectInputBeforeThought(4, 'Second input')
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'Open sidebar',exact:true})).toBeVisible()
  await expect.poll(async () => (await page.locator('.ppm-world-actions').last().boundingBox())!.x).toBeLessThan(100)
  await expect(results).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/papermoon-chat-actions-narrow.png',fullPage:true})
  await page.setViewportSize({width:1280,height:900})
  await page.getByRole('tab',{name:'Trajectory',exact:true}).click()
  await expect(nodes).toHaveCount(5)
  await expect(nodes.nth(2)).toContainText('Floor 2');await expect(nodes.nth(4)).toContainText('Floor 2')
  await expect(nodes.nth(2)).toContainText('Turn 2');await expect(nodes.nth(4)).toContainText('Turn 4')
  await nodes.nth(4).click()
  await expect(page.getByRole('row').filter({hasText:'Second input'}).last().locator('[data-role-kind]')).toHaveAttribute('data-role-kind','user')
  await toolbar.getByRole('button',{name:'Rewritten context',exact:true}).click()
  await expect(toolbar).toContainText('Turn 4')
  await page.reload()
  await expect(page.getByRole('tab',{name:'Trajectory',exact:true})).toHaveAttribute('aria-selected','true')
  await expect(toolbar).toContainText('Turn 4')
  await expect(toolbar.getByRole('button',{name:'Rewritten context',exact:true})).toHaveAttribute('aria-pressed','true')
  await nodes.first().click()
  await expect(toolbar.getByRole('button',{name:'Rewritten context',exact:true})).toBeDisabled()
  await expect(page.getByRole('row').filter({hasText:'Frozen opening'}).first()).toBeVisible()
  await nodes.nth(3).click()
  await expect(toolbar.getByRole('button',{name:'Rewritten context',exact:true})).toHaveAttribute('aria-pressed','true')
  await expect(page.getByRole('row').filter({hasText:'Context tail 2'}).first()).toBeVisible()
  await nodes.first().focus();await page.keyboard.press('ArrowDown');await expect(nodes.nth(1)).toBeFocused()
  await nav.getByRole('button',{name:'Collapse worldlines',exact:true}).click()
  await expect(nav).toHaveCSS('width','44px')
  await expect(nav.locator('.ppm-navigation-body')).toHaveJSProperty('inert',true)
  await nav.evaluate(element=>element.addEventListener('transitionrun',event=>{if((event as TransitionEvent).propertyName==='width')element.setAttribute('data-width-transition','true')}))
  await nav.getByRole('button',{name:'Open worldlines',exact:true}).click()
  // The retained panel animates its width; its scroll position and nodes survive collapse.
  await expect(nav).toHaveAttribute('data-width-transition','true')
  await expect(nav).toHaveCSS('width','240px')
  await expect(nodes).toHaveCount(5)
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(nav).toHaveCSS('transition-duration','0s')
  await page.emulateMedia({reducedMotion:'no-preference'})
  await page.screenshot({path:'test-results/papermoon-dual-trajectory.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('button',{name:'Open sidebar',exact:true})).toBeVisible()
  await expect.poll(async()=> (await toolbar.boundingBox())!.x).toBeLessThan(100)
  await nav.getByRole('button',{name:'Collapse worldlines',exact:true}).click()
  await expect(toolbar.getByRole('button',{name:'Switch to here',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await expect(nav).toHaveCSS('width','44px')
  await expect(nav.locator('.ppm-navigation-body')).not.toBeVisible()
  await page.screenshot({path:'test-results/papermoon-dual-trajectory-narrow.png',fullPage:true})
  await nav.getByRole('button',{name:'Open worldlines',exact:true}).click();await expect(nodes.nth(3)).toBeVisible()
  await expect(nav).toHaveCSS('width','240px')
  await page.screenshot({path:'test-results/papermoon-dual-trajectory-drawer.png',fullPage:true})
  expect(errors).toEqual([])
})
