import { test, expect, type Page } from '@playwright/test'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../story-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeAll(async () => { server = await startEditorServer(['--patch', resolve('plugins/writer-sessions/e2e/fixture.patch.yml')]) })
test.afterAll(async () => { await server?.stop() })
async function call(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  expect(response.status()).toBe(200)
  const result = (await response.json()).result
  expect(result.ok, JSON.stringify(result)).toBe(true)
  return result.value
}
test('frozen opening appears before a model request and survives reload, Fork and source deletion', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) })
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  const project = await call(page, 'papermoon/createProject', { name: 'Performance project' })
  const script = await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Frozen opening', defaultLanguage: 'en' })
  await call(page, 'papermoon/save', { scriptId: script.id, expectedSequence: 0, operations: [{ kind: 'create-file', path: 'story.js', source: 'module.exports={systemPrompt:"Exact {{literal}} system.",messages:[{name:"Opening",role:"assistant",content:"Assistant fixture text."},{name:"Background",role:"user",content:"Background fixture text."},{role:"user",content:""}]}' }] })
  const revision = await call(page, 'papermoon/commit', { scriptId: script.id, expectedSequence: 1, description: 'First playable revision' })
  expect(revision.committed).toBe(true)
  await page.goto(new URL('/#papermoon/' + script.id, server.url).href)
  await expect(page.getByRole('button', { name: 'Start performance', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Compile', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Start performance', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toContainText('First playable revision')
  await expect(dialog.getByRole('button', { name: 'Model', exact: true })).toContainText('Fixture model')
  await dialog.getByRole('button', { name: 'Start performance', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.locator('.ppm-authored').first()).toContainText('Assistant fixture text.')
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  expect(existsSync(join(server.directory, 'data/requests.jsonl'))).toBe(false)
  const initialList = await call(page, 'session/list', { args: { _request: {} } })
  expect(initialList.items.filter((item: { blank: boolean }) => !item.blank)).toHaveLength(1)
  const found = await call(page, 'session/search', { args: { request: { query: 'Background fixture' } } })
  expect(found.items).toHaveLength(1)
  await page.reload()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await input.fill('User fixture input.'); await input.press('Enter')
  await expect(page.locator('p').filter({ hasText: /^Fixture reply\.$/ })).toBeVisible()
  await expect(page.locator('.ppm-authored')).toHaveCount(3)
  const requests = () => readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(request => !request.purpose)
  expect(requests()).toHaveLength(1)
  expect(requests()[0].messages.map((m: { role: string }) => m.role)).toEqual(['system', 'assistant', 'user', 'user', 'user'])
  expect(requests()[0].messages.map((m: { content: { text: string }[] }) => m.content.map(b => b.text).join(''))).toEqual(['Exact {{literal}} system.', 'Assistant fixture text.', 'Background fixture text.', '', 'User fixture input.'])
  expect(requests()[0].tools ?? []).toEqual([])
  await page.screenshot({ path: 'test-results/papermoon-performance.png', fullPage: true })
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByText('Assistant fixture text.', { exact: true }).first()).toBeVisible()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  const state = await call(page, 'session/list', { args: { _request: {} } })
  const sessionId = state.items.find((item: { agentPreset?: string }) => item.agentPreset === 'papermoon-moderator')?.sessionId ?? state.items[0].sessionId
  const child = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: child.sessionId })).fixed.revisionId).toBe(revision.revision.id)
  await call(page, 'papermoon/deleteScript', { scriptId: script.id })
  const afterDeletion = await call(page, 'session/fork', { args: { request: { sessionId } } })
  expect((await call(page, 'papermoon-performances/state', { sessionId: afterDeletion.sessionId })).sourceMissing).toBe(true)
  await call(page, 'session/prompt', { args: { request: { sessionId: child.sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: 'Continue' }] } } })
  await expect.poll(() => requests().length).toBe(2)
  expect(requests()[1].messages.filter((m: { content: { text: string }[] }) => m.content.some(b => b.text === 'Assistant fixture text.'))).toHaveLength(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
