import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../story-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeEach(async () => { server = await startEditorServer(['--patch', resolve('plugins/writer-sessions/e2e/fixture.patch.yml')]) })
test.afterEach(async () => { await server?.stop() })
async function call(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  expect(response.status()).toBe(200)
  const result = (await response.json()).result
  expect(result.ok, JSON.stringify(result)).toBe(true)
  return result.value
}
test('writer workspace sends exact context and retains its accepted configuration', async ({ page }) => {
  let sessionId: string | undefined
  page.on('request', request => { if (request.method() === 'POST') { const data = request.postDataJSON(); if (data?.method === 'session/prompt') sessionId = data.payload.args.request.sessionId } })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('Failed to load resource')) errors.push(message.text()) })
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  await page.getByRole('button', { name: 'New session', exact: true }).last().click()
  const project = await call(page, 'papermoon/createProject', { name: 'Workspace project' })
  const script = await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Same name', defaultLanguage: 'en' })
  await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Other script', defaultLanguage: 'en' })
  const definition = { name: 'Fixture writer', systemPrompt: 'Exact {{literal}} system.', messages: [{ id: 'a', name: 'First', role: 'user', content: 'Preset user' }, { id: 'b', name: 'Second', role: 'assistant', content: 'Preset assistant' }], metadata: {} }
  const writer = await call(page, 'papermoon-writers/create', definition)
  await page.getByRole('button', { name: 'Standard mode', exact: true }).click()
  await page.getByRole('menuitem', { name: /编剧/ }).click()
  await page.getByRole('button', { name: /Choose script/ }).click()
  await page.getByRole('button', { name: /Same name.*Workspace project/ }).click()
  await page.getByRole('button', { name: /Choose writer/ }).click()
  await page.getByRole('menuitem', { name: 'Fixture writer', exact: true }).click()
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await expect(input).toHaveAttribute('contenteditable', 'true')
  await input.fill('Please inspect the script.')
  await input.press('Enter')
  await expect(page.getByText('Fixture reply.', { exact: true })).toBeVisible()
  const fixed = page.locator('.pws-chip').filter({ hasText: 'Fixture writer' })
  await expect(fixed).toBeDisabled()
  const writerBounds = await fixed.boundingBox(), tabBounds = await page.getByRole('tab', { name: 'Chat', exact: true }).boundingBox()
  expect(writerBounds!.y + writerBounds!.height).toBeLessThanOrEqual(tabBounds!.y)
  await expect(page.getByRole('button', { name: 'Open script', exact: true })).toHaveCount(0)
  await expect(page.locator('[role=treeitem]').filter({ hasText: 'Workspace project / Same name' })).toHaveCount(0)
  await expect(page.locator('[role=treeitem]').filter({ hasText: 'Same name' }).first()).toBeVisible()
  await page.screenshot({ path: 'test-results/papermoon-writer-header.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Writer management', exact: true })).toHaveAttribute('data-wide', 'false')
  await expect(fixed).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await expect.poll(async () => { const bounds = await fixed.boundingBox(); return bounds!.x + bounds!.width }).toBeLessThanOrEqual(390)
  await expect.poll(async () => {
    const writer = await fixed.boundingBox(), utilities = await page.locator('header [class*=headerUtilities]').boundingBox()
    return writer!.x + writer!.width <= utilities!.x
  }).toBe(true)
  await page.screenshot({ path: 'test-results/papermoon-writer-header-narrow.png', fullPage: true, animations: 'disabled' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.locator('.pws-context summary')).toBeVisible()
  await page.locator('.pws-context summary').click()
  await expect(page.locator('.pws-context pre')).toHaveText(['Preset user', 'Preset assistant'])
  const requests = readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line))
  await test.info().attach('model-request', { body: JSON.stringify(requests[0], null, 2), contentType: 'application/json' })
  expect(requests[0].messages.map((message: { role: string }) => message.role)).toEqual(['system', 'user', 'assistant', 'user'])
  expect(requests[0].messages.map((message: { content: { text: string }[] }) => message.content.map(block => block.text).join(''))).toEqual([definition.systemPrompt, 'Preset user', 'Preset assistant', 'Please inspect the script.'])
  expect(requests[0].tools.map((tool: { name: string }) => tool.name)).toContain('story_status')
  await call(page, 'papermoon-writers/delete', { id: writer.id, expectedSequence: writer.sequence })
  await page.reload()
  await expect(fixed).toBeDisabled()
  await expect(page.locator('.pws-context summary')).toHaveCount(1)
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.getByText('Preset assistant', { exact: true }).first()).toBeVisible()
  expect(sessionId).toBeTruthy()
  const child = await call(page, 'session/fork', { args: { request: { sessionId } } })
  const childView = await call(page, 'papermoon-writer-sessions/state', { sessionId: child.sessionId })
  expect(childView.fixed.writer).toMatchObject({ id: writer.id, systemPrompt: definition.systemPrompt })
  const send = { sessionId: child.sessionId, requestId: crypto.randomUUID(), mode: 'queue', content: [{ type: 'text', text: 'Continue from the inherited context.' }] }
  await call(page, 'session/prompt', { args: { request: send } })
  await call(page, 'session/prompt', { args: { request: send } })
  await expect.poll(() => readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').length).toBe(3)
  const last = JSON.parse(readFileSync(join(server.directory, 'data/requests.jsonl'), 'utf8').trim().split('\n').at(-1)!)
  expect(last.messages.filter((message: { content: { text: string }[] }) => message.content.some(block => block.text === 'Preset assistant'))).toHaveLength(1)
  await call(page, 'papermoon/deleteScript', { scriptId: script.id })
  await page.reload()
  await expect(page.getByText('This script has been deleted. History is still available.', { exact: true }).first()).toBeVisible()
  const deleted = await call(page, 'papermoon-writer-sessions/state', { sessionId: child.sessionId })
  expect(deleted.targetMissing).toBe(true)
  expect(errors).toEqual([])
  expect(script.id).toBeTruthy()
})

test('mode changes preserve unsent text and clear incompatible workspace choices', async ({ page }) => {
  await page.addLocatorHandler(page.getByRole('button', { name: 'Continue', exact: true }), async () => { await page.getByRole('button', { name: 'Continue', exact: true }).click() })
  await page.goto(server.url)
  await page.getByRole('button', { name: 'New session', exact: true }).last().click()
  const project = await call(page, 'papermoon/createProject', { name: 'Workspace project' })
  await call(page, 'papermoon/createScript', { projectId: project.id, name: 'Other script', defaultLanguage: 'en' })
  await page.getByRole('button', { name: 'Standard mode', exact: true }).click()
  await page.getByRole('menuitem', { name: /编剧/ }).click()
  await page.getByRole('button', { name: /Choose script/ }).click()
  await page.getByRole('button', { name: /Other script.*Workspace project/ }).click()
  await expect(page.getByRole('button', { name: 'Manage writers', exact: true }).first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeDisabled()
  await call(page, 'papermoon-writers/create', { name: 'Switch writer', systemPrompt: 'Write.', messages: [], metadata: {} })
  await page.getByRole('button', { name: 'Choose writer', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch writer', exact: true }).click()
  const input = page.getByRole('textbox').filter({ visible: true }).last()
  await expect(input).toHaveAttribute('contenteditable', 'true')
  await input.pressSequentially('Keep this unfinished instruction.')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '编剧', exact: true }).click()
  await page.getByRole('menuitem', { name: /^Standard mode / }).click()
  await expect(page.getByRole('button', { name: /Choose script/ })).toHaveCount(0)
  await expect(input).toHaveText('Keep this unfinished instruction.')
  await page.getByRole('button', { name: 'Standard mode', exact: true }).click()
  await page.getByRole('menuitem', { name: /编剧/ }).click()
  await expect(page.getByRole('button', { name: /Choose script/ })).toBeVisible()
  await expect(input).toHaveText('Keep this unfinished instruction.')
  await page.getByRole('button', { name: /Choose script/ }).click()
  await page.getByRole('button', { name: /Other script.*Workspace project/ }).click()
  await page.getByRole('button', { name: 'Choose writer', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Switch writer', exact: true }).click()
  await expect(input).toHaveText('Keep this unfinished instruction.')
  await expect(page.getByRole('button', { name: 'Send message', exact: true })).toBeEnabled()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.pws-chip').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
