import { test, expect, type Page } from '@playwright/test'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../playbook-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeEach(async ({ browserName: _browserName }, info) => {
  const args = ['--patch', resolve('plugins/story-mode/e2e/fixture.patch.yml')]
  if (info.tags.includes('@invalid-default')) args.push('--patch', resolve('plugins/story-mode/e2e/invalid-default.patch.yml'))
  server = await startEditorServer(args)
})
test.afterEach(async () => { if (test.info().status !== test.info().expectedStatus) console.log(server?.logs()); await server?.stop() })
async function rpc(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  return (await response.json()).result
}
async function call(page: Page, name: string, payload: unknown) {
  const result = await rpc(page, name, payload)
  expect(result.ok, JSON.stringify(result)).toBe(true)
  return result.value
}
function requests() {
  const path = join(server.directory, 'data/requests.jsonl')
  return existsSync(path) ? readFileSync(path, 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(value => !value.purpose) : []
}
const next = (page: Page) => page.locator('.pm-story-progress').getByRole('button', { name: 'Continue', exact: true })
const editor = (page: Page) => page.locator('[data-composer-input]')
async function atStep(page: Page, value: number) {
  await expect(page.locator('.pm-story-progress')).toHaveAttribute('data-step', String(value))
  if (value < 6) {
    await expect(page.locator('.pm-story-progress [aria-current="step"]')).toHaveCount(1)
    await expect(page.locator('.pm-story-progress li .pm-story-guidance')).toHaveCount(1)
  }
}
async function start(page: Page) {
  await page.goto(server.url)
  const notice = page.getByRole('dialog', { name: 'Internal Testing Notice', exact: true })
  await notice.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(notice).toHaveCount(0)
  await page.getByRole('button', { name: 'Story Mode', exact: true }).click()
  await page.getByRole('button', { name: 'Enter chapter', exact: true }).click()
  await atStep(page, 1)
}
async function reachPractice(page: Page, enter = true, capture = false) {
  if (enter) await start(page)
  const count = requests().length
  await expect(page.locator('.pm-story-introduction').getByRole('button')).toHaveCount(1)
  await expect(page.locator('.pm-story-introduction-copy')).toContainText('Welcome to PaperMoon’s Story Mode.')
  await expect(next(page)).toBeEnabled()
  if (capture) {
    await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/introduction.png' })
    await page.emulateMedia({ colorScheme: 'dark' })
    await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/introduction-dark.png' })
    await page.emulateMedia({ colorScheme: 'light' })
  }
  await next(page).click()
  await atStep(page, 2)
  await expect(page.locator('[data-conversation-content]')).toBeVisible()
  await expect(page.locator('header[data-window-drag]')).toBeVisible()
  await expect(page.getByRole('tab', { name: 'Chat', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tab', { name: 'Trajectory', exact: true })).toBeVisible()
  await expect(page.locator('header[data-window-drag]')).toContainText('hi')
  await expect(editor(page)).toHaveAttribute('contenteditable', 'false')
  await expect(page.getByText('Read-only conversation', { exact: true })).toBeVisible()
  await expect(page.getByText('Hi! How can I help you today?', { exact: true })).toBeVisible()
  if (capture) await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/example.png' })
  const example = (await call(page, 'papermoon-story/state', {})).example
  const refused = await rpc(page, 'session/prompt', { args: { request: { sessionId: example.id, requestId: crypto.randomUUID(), content: [{ type: 'text', text: 'do not send' }] } } })
  expect(refused.ok).toBe(false)
  await next(page).click()
  await atStep(page, 3)
  await expect(page.getByRole('tab', { name: 'Chat', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(next(page)).toBeDisabled()
  await expect(page.locator('.pm-guidance-hint')).toBeVisible()
  await page.getByRole('button', { name: 'Plugins', exact: true }).click()
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  await expect(next(page)).toBeDisabled()
  await expect(page.getByRole('switch', { name: 'Enable Story Mode', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'New session', exact: true }).last().click()
  await expect(page.locator('.pm-guidance-hint')).toBeVisible()
  const tab = page.getByRole('tab', { name: 'Trajectory', exact: true })
  const target = await tab.boundingBox()
  const highlight = await page.locator('.pm-guidance-outline').boundingBox()
  expect(highlight!.x).toBeCloseTo(target!.x - 4)
  expect(highlight!.width).toBeCloseTo(target!.width + 8)
  if (capture) {
    await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/hint.png' })
    const viewport = page.viewportSize()!
    await page.setViewportSize({ width: 390, height: 844 })
    let previousX = Number.NaN
    let stableFrames = 0
    await expect.poll(async () => {
      const x = (await tab.boundingBox())?.x ?? 999
      stableFrames = x < 200 && Math.abs(x - previousX) < 0.1 ? stableFrames + 1 : 0
      previousX = x
      return stableFrames
    }, { intervals: [100] }).toBeGreaterThanOrEqual(2)
    await expect(page.locator('.pm-guidance-hint')).toBeVisible()
    await expect.poll(async () => {
      const anchor = await tab.boundingBox()
      const ring = await page.locator('.pm-guidance-outline').boundingBox()
      return anchor && ring ? Math.abs(ring.x - anchor.x + 4) : 100
    }).toBeLessThan(1)
    await expect.poll(async () => {
      const hint = await page.locator('.pm-guidance-hint').boundingBox()
      return hint ? hint.x + hint.width : 999
    }).toBeLessThanOrEqual(390)
    await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/hint-narrow.png' })
    await page.setViewportSize(viewport)
  }
  await page.keyboard.press('Escape')
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  await expect(next(page)).toBeDisabled()
  await page.getByRole('button', { name: 'Show hint', exact: true }).click()
  await expect(page.locator('.pm-guidance-hint')).toBeVisible()
  // Native keyboard activation, not an overlay click or a chapter-generated navigation.
  await tab.focus()
  await page.keyboard.press('Enter')
  await expect(tab).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('[data-conversation-content]')).toContainText('Initial System Prompt')
  await expect(next(page)).toBeEnabled()
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  if (capture) await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/trajectory.png' })
  await next(page).click()
  await atStep(page, 4)
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  await expect(page.getByText('Message', { exact: true })).toBeVisible()
  await expect(page.getByText('Into the Unknown', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Commands', exact: true })).toBeHidden()
  expect(requests()).toHaveLength(count)
}
async function select(page: Page, kind: 'Model' | 'Effort', value: string) {
  await page.getByRole('button', { name: /^Select model/ }).click()
  await page.getByRole('menuitem', { name: new RegExp('^' + kind) }).click()
  await page.getByRole('menuitemradio', { name: value, exact: true }).click()
}
async function send(page: Page, text: string) {
  await editor(page).fill(text)
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
}
test('native pages with sidebar guidance, isolated example, exact requests and recovery', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('ERR_INCOMPLETE_CHUNKED_ENCODING')) errors.push(message.text()) })
  await reachPractice(page, true, true)
  const before = await call(page, 'papermoon-story/state', {})
  const defaults = (await call(page, 'session/modelCatalog', { args: {} })).default
  await page.getByRole('button', { name: 'New session', exact: true }).last().click()
  await atStep(page, 4)
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  await select(page, 'Effort', 'off')
  await expect(page.getByText('For this exercise, choose off to turn thinking off.', { exact: true })).toHaveCount(0)
  await send(page, '/hello @world')
  await atStep(page, 5)
  await expect(page.getByRole('tab', { name: 'Chat', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('button', { name: 'Complete chapter', exact: true })).toBeDisabled()
  await expect(page.locator('.pm-guidance-hint')).toBeVisible()
  const sent = requests()[0]
  expect(sent.reasoningEffort).toBe('off')
  expect(sent.tools ?? []).toEqual([])
  expect(sent.messages.map((message: { role: string }) => message.role)).toEqual(['system', 'user'])
  expect(sent.messages.map((message: { content: { text: string }[] }) => message.content.map(block => block.text).join(''))).toEqual(['You are a helpful assistant', '/hello @world'])
  expect((await call(page, 'session/modelCatalog', { args: {} })).default).toEqual(defaults)
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  await select(page, 'Model', 'plain-model')
  await send(page, 'second reply')
  await expect.poll(() => requests().length).toBe(2)
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeHidden()
  const firstTurn = (await call(page, 'papermoon-story/state', {})).attempt.successfulTurn
  expect(firstTurn).toBe(1)
  await page.reload()
  await atStep(page, 5)
  await expect(page.locator('[data-conversation-content]')).toContainText('Hello from the fixture.')
  expect(requests()).toHaveLength(2)
  expect((await call(page, 'papermoon-story/state', {})).attempt.successfulTurn).toBe(firstTurn)
  await expect(page.getByRole('button', { name: 'Complete chapter', exact: true })).toBeDisabled()
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  const view = (await call(page, 'papermoon-story/state', {})).conversation
  const firstReply = view.events.findLast((event: { type: string; data: { turn: number } }) => event.type === 'assistant/message' && event.data.turn === firstTurn)
  await page.locator(`[data-conversation-view=trajectory] [data-kind=message][data-source-seq="${firstReply.seq}"]`).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Complete chapter', exact: true })).toBeEnabled()
  await page.reload()
  await atStep(page, 5)
  await expect(page.getByRole('tab', { name: 'Trajectory', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  await page.getByRole('button', { name: 'Complete chapter', exact: true }).click()
  await expect(page.getByText('You have completed hello world. You can keep chatting, return to the chapter list, or restart.', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'Chat', exact: true }).click()
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  await send(page, 'fail')
  await expect.poll(() => requests().length).toBe(3)
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeHidden()
  await atStep(page, 6)
  await send(page, 'keep chatting')
  await expect.poll(() => requests().length).toBe(4)
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeHidden()
  await page.reload()
  await atStep(page, 6)
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  const completed = (await call(page, 'papermoon-story/state', {})).attempt
  expect(completed.successfulTurn).toBe(firstTurn)
  expect(completed.trajectorySeen).toBe(true)
  expect(requests()).toHaveLength(4)
  const list = await call(page, 'session/list', { args: { _request: {} } })
  expect(JSON.stringify(list)).not.toContain(before.attempt.sessionId)
  expect(JSON.stringify(list)).not.toContain(before.attempt.id)
  await page.getByRole('button', { name: 'Restart', exact: true }).click()
  await reachPractice(page, false)
  expect((await call(page, 'papermoon-story/state', {})).attempt.sessionId).not.toBe(before.attempt.sessionId)
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/chapter.png' })
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/chapter-dark.png' })
  await page.emulateMedia({ colorScheme: 'light' })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('navigation', { name: '第零章 · hello world', exact: true })).toBeVisible()
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/chapter-zh.png' })
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('button', { name: '中文', exact: true }).click()
  await page.getByText('English', { exact: true }).click()
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Chapter 0 · hello world', exact: true })).toBeVisible()
  await expect(editor(page)).toBeVisible()
  const bounds = await editor(page).boundingBox()
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390)
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/chapter-narrow.png' })
  await page.getByRole('button', { name: 'Chapter 0 · hello world', exact: true }).click()
  await expect(page.locator('.pm-story-progress li .pm-story-guidance')).toBeVisible()
  expect(errors).toEqual([])
})
test('native model controls, failure and stop keep the exercise retryable', async ({ page }) => {
  await reachPractice(page)
  await select(page, 'Model', 'low-model')
  await expect(page.getByText('For this exercise, use the lowest available effort.', { exact: true })).toBeVisible()
  await select(page, 'Effort', 'low')
  await select(page, 'Model', 'plain-model')
  await send(page, 'fail')
  await expect(page.getByText(/The last request did not complete/)).toBeVisible()
  expect(requests()[0].reasoningEffort).toBeUndefined()
  await send(page, 'wait')
  await page.getByRole('button', { name: 'Stop generating', exact: true }).click()
  await page.reload()
  await atStep(page, 4)
  expect(requests()).toHaveLength(2)
  await send(page, 'retry')
  await atStep(page, 5)
})
test('native plugin toggle releases private views and restores the existing attempt', async ({ page }) => {
  await reachPractice(page)
  const before = await call(page, 'papermoon-story/state', {})
  await send(page, 'wait')
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Plugins', exact: true }).click()
  const toggle = page.getByRole('switch', { name: 'Enable Story Mode', exact: true })
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-checked', 'false')
  await expect(page.getByRole('button', { name: 'Story Mode', exact: true })).toHaveCount(0)
  await page.reload()
  await page.getByRole('button', { name: 'Plugins', exact: true }).click()
  await toggle.click()
  await page.getByRole('button', { name: 'Story Mode', exact: true }).click()
  await page.getByRole('button', { name: 'Continue chapter', exact: true }).click()
  await atStep(page, 4)
  await expect(editor(page)).toHaveAttribute('contenteditable', 'true')
  expect((await call(page, 'papermoon-story/state', {})).attempt.sessionId).toBe(before.attempt.sessionId)
  expect(requests()).toHaveLength(1)
})

test('chapter exit restores ordinary controls and keeps private sessions out of the sidebar', async ({ page }) => {
  await reachPractice(page)
  const attempt = (await call(page, 'papermoon-story/state', {})).attempt
  await page.getByRole('button', { name: 'Chapter list', exact: true }).click()
  await expect(page.locator('.pm-story-progress')).toHaveCount(0)
  await expect(page.locator('.pm-guidance')).toHaveCount(0)
  await page.getByRole('button', { name: 'New session', exact: true }).last().click()
  await expect(page.getByRole('button', { name: 'Add files or run commands', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Standard mode/ })).toBeVisible()
  expect(await page.locator('[data-conversation-content]').getAttribute('data-conversation-session')).not.toBe(attempt.sessionId)
  const list = await call(page, 'session/list', { args: { _request: {} } })
  expect(JSON.stringify(list)).not.toContain(attempt.sessionId)
  expect(JSON.stringify(list)).not.toContain(attempt.id)
  await page.getByRole('button', { name: 'Story Mode', exact: true }).click()
  await page.getByRole('button', { name: 'Continue chapter', exact: true }).click()
  await atStep(page, 4)
  await expect(page.locator('[data-conversation-content]')).toHaveAttribute('data-conversation-session', attempt.sessionId)
  expect(requests()).toHaveLength(0)
})

test('introduction checks current configuration and recovers without a visit requirement', async ({ page }) => {
  const availability = join(server.directory, 'data/availability')
  writeFileSync(availability, 'missing')
  await start(page)
  await expect(page.getByText('Open model configuration and finish configuring at least one model before continuing.', { exact: true })).toBeVisible()
  await expect(next(page)).toBeDisabled()
  await page.getByRole('button', { name: 'Open model configuration', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pm-story-introduction')).toBeVisible()
  await expect(next(page)).toBeDisabled()
  writeFileSync(availability, 'error')
  await expect(page.locator('.pm-story-progress [role=status]')).toContainText('Could not read model configuration. Please retry.')
  await expect(next(page)).toBeDisabled()
  writeFileSync(availability, 'ready')
  await page.locator('.pm-story-progress').getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(next(page)).toBeEnabled()
  await atStep(page, 1)
  await page.getByRole('button', { name: 'Restart', exact: true }).click()
  await expect(next(page)).toBeEnabled()
  expect(requests()).toHaveLength(0)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('button', { name: 'English', exact: true }).click()
  await page.getByText('中文', { exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pm-story-introduction-copy')).toContainText('欢迎来到 PaperMoon 的故事模式。')
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/introduction-zh.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: '第零章 · hello world', exact: true })).toBeVisible()
  await expect(page.locator('.pm-story-progress')).toHaveCount(0)
  await expect(page.locator('.pm-story-introduction').getByRole('button', { name: '打开模型配置', exact: true })).toBeVisible()
  await page.screenshot({ animations: 'disabled', path: 'test-results/story-mode/introduction-zh-narrow.png' })
})

test('an invalid default does not block introduction or select a replacement practice model', { tag: '@invalid-default' }, async ({ page }) => {
  await reachPractice(page)
  const state = await call(page, 'papermoon-story/state', {})
  expect(state.conversation.events.some((event: { type: string }) => event.type === 'model/selection')).toBe(false)
  await select(page, 'Model', 'plain-model')
  await send(page, 'chosen explicitly')
  await atStep(page, 5)
  expect(requests()[0].model).toBe('plain-model')
  expect((await call(page, 'session/modelCatalog', { args: {} })).default.model).toBe('not-listed')
})

test('later replies do not satisfy viewing the first successful trajectory', async ({ page }) => {
  await reachPractice(page)
  for (let index = 0; index < 8; index++) {
    await send(page, `message ${index}`)
    await expect.poll(() => requests().length).toBe(index + 1)
    await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeHidden()
  }
  await atStep(page, 5)
  const before = await call(page, 'papermoon-story/state', {})
  expect(before.attempt.successfulTurn).toBe(1)
  const firstReply = before.conversation.events.findLast((event: { type: string; data: { turn: number } }) => event.type === 'assistant/message' && event.data.turn === 1)
  await page.getByRole('tab', { name: 'Trajectory', exact: true }).click()
  await expect(page.locator('[data-conversation-view=trajectory] [data-trajectory-scroll]')).toBeVisible()
  // The native ledger initially shows its tail. Later visible replies cannot acknowledge the first one.
  await expect(page.getByRole('button', { name: 'Complete chapter', exact: true })).toBeDisabled()
  expect((await call(page, 'papermoon-story/state', {})).attempt.trajectorySeen).toBe(false)
  await page.locator('[data-trajectory-scroll]').evaluate(element => element.scrollTo({ top: 0 }))
  await page.locator(`[data-kind=message][data-source-seq="${firstReply.seq}"]`).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Complete chapter', exact: true })).toBeEnabled()
  expect((await call(page, 'papermoon-story/state', {})).attempt.successfulTurn).toBe(1)
})
