import { test, expect, type Page } from '@playwright/test'
import { existsSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { startEditorServer } from '../../playbook-editor/e2e/server.ts'
let server: Awaited<ReturnType<typeof startEditorServer>>
test.beforeEach(async () => { server = await startEditorServer(['--patch', resolve('plugins/story-mode/e2e/fixture.patch.yml')]) })
test.afterEach(async () => { if (test.info().status !== test.info().expectedStatus) console.log(server?.logs()); await server?.stop() })
async function rpc(page: Page, name: string, payload: unknown) {
  const response = await page.request.post(new URL('/api/' + name, server.url).href, { data: { type: 'client-request', rpcId: crypto.randomUUID(), method: name, payload } })
  return (await response.json()).result
}
async function call(page: Page, name: string, payload: unknown) { const result = await rpc(page, name, payload); expect(result.ok, JSON.stringify(result)).toBe(true); return result.value }
function requests() { const path = join(server.directory, 'data/requests.jsonl'); return existsSync(path) ? readFileSync(path, 'utf8').trim().split('\n').map(line => JSON.parse(line)).filter(value => !value.purpose) : [] }
const guide = (page: Page) => page.locator('.pm-story-guide:visible')
const next = (page: Page) => guide(page).getByRole('button', { name: 'Continue', exact: true })
async function select(page: Page, label: string, choice: string) { await page.getByRole('button', { name: label, exact: true }).click(); await page.getByRole('menuitem', { name: choice, exact: true }).click() }
async function section(page: Page, index: number) { await expect(guide(page)).toHaveAttribute('data-story-section', String(index)) }
async function enter(page: Page, dismissHint = false) {
  await page.goto(server.url)
  const notice = page.getByRole('dialog', { name: 'Internal Testing Notice', exact: true })
  await notice.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Story Mode', exact: true }).click()
  await page.getByRole('textbox', { name: 'Save name', exact: true }).fill('Keeper')
  if (dismissHint) await page.screenshot({ path: 'test-results/story-mode/save-entrance.png' })
  await page.getByRole('button', { name: 'Create save', exact: true }).click()
  await expect(guide(page)).toHaveCount(0)
  await expect(page.locator('.pm-guidance-hint')).toContainText('Save created. Open the right sidebar here to view Story Guide.')
  await expect(page.locator('.pm-guidance')).toHaveAttribute('data-guidance-target', '[data-sidebar-right-expand]')
  if (dismissHint) {
    await page.screenshot({ path: 'test-results/story-mode/creation-hint.png' })
    await page.keyboard.press('Escape')
    await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
    await expect(guide(page)).toHaveCount(0)
  }
  await page.getByRole('button', { name: 'Open right sidebar', exact: true }).click()
  await section(page, 1)
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  return (await call(page, 'papermoon-story/list', {}))[0].id as string
}
async function send(page: Page, text: string) { await page.locator('[data-composer-input]').fill(text); await page.getByRole('button', { name: 'Send message', exact: true }).click() }
test('five sections author an independent save, freeze the request and review the first response', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(String(error)))
  const id = await enter(page)
  expect((await call(page, 'papermoon-story/state', { playbookId: id })).progress.sessionId).toBeUndefined()
  const sessions = (await call(page, 'session/list', { args: { _request: {} } })).items
  expect(sessions.every((session: { projections: { values: { agentPreset: string } } }) => session.projections.values.agentPreset === 'standard')).toBe(true)
  await expect(page.locator('.pm-authoring')).toHaveCount(0)
  await next(page).click(); await section(page, 2)
  await expect(page.locator('[data-story-unlock="opening"]')).toContainText('Newly unlocked')
  await expect(next(page)).toBeDisabled()
  await page.getByRole('button', { name: 'Add message', exact: true }).click()
  await page.locator('.cm-content').fill('Welcome to the light.\nWhere did you find that map?')
  await page.getByRole('button', { name: 'Add message', exact: true }).click()
  const secondMessage = page.locator('.pm-opening-message').nth(1)
  await secondMessage.locator('.cm-content').fill('The harbor is quiet.')
  await secondMessage.getByRole('button', { name: 'Message role', exact: true }).click()
  await page.getByRole('menuitem', { name: 'user', exact: true }).click()
  await secondMessage.getByRole('button', { name: 'Move up', exact: true }).focus()
  await page.keyboard.press('Space')
  await expect(page.locator('.pm-opening-message').first().locator('.cm-content')).toContainText('The harbor is quiet.')
  for (const colorScheme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme })
    const roleControl = page.locator('.pm-opening-message').first().getByRole('button', { name: 'Message role', exact: true })
    await roleControl.click()
    const menu = page.getByRole('menu')
    await expect(menu).toHaveCSS('background-color', /^rgb\([\d, ]+\)$/)
    await expect(menu).toHaveCSS('opacity', '1')
    for (const role of ['user', 'assistant']) {
      const selector = `[data-message-role="${role}"]`
      const expected = await guide(page).locator(`tbody ${selector}`).evaluate(element => {
        const style = getComputedStyle(element)
        return { color: style.color, background: style.backgroundColor }
      })
      for (const badge of [page.locator(`.pm-opening-message ${selector}`), menu.locator(selector)]) {
        await expect(badge).toHaveCSS('color', expected.color)
        await expect(badge).toHaveCSS('background-color', expected.background)
      }
    }
    await page.screenshot({ path: `test-results/story-mode/role-menu-${colorScheme}.png` })
    await page.keyboard.press('Escape')
  }
  await page.emulateMedia({ colorScheme: 'light' })
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(next(page)).toBeEnabled(); await next(page).click(); await section(page, 3)
  await expect(page.locator('[data-story-unlock="system"]')).toContainText('System prompt editor')
  await page.getByRole('tab', { name: 'System prompt', exact: true }).click()
  const source = 'You are the lighthouse keeper.\n<voice>patient and curious'
  await page.locator('.cm-content').fill(source)
  await select(page, 'Syntax highlighting', 'XML')
  expect((await page.locator('.cm-line').allTextContents()).join('\n')).toBe(source)
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await expect(page.locator('[data-story-unlock="system"]')).toHaveCount(0)
  await next(page).click(); await section(page, 4)
  await select(page, 'Model', 'story-fixture · off-model')
  await page.getByRole('button', { name: 'Use this model', exact: true }).click()
  await expect(next(page)).toBeEnabled(); await next(page).click(); await section(page, 5)
  await expect(page.locator('[data-story-unlock="performance"]')).toContainText('Reasoning effort and performance')
  await select(page, 'Reasoning effort', 'high')
  await page.getByRole('button', { name: 'Use this model', exact: true }).click()
  expect(requests()).toHaveLength(0)
  const defaults = (await call(page, 'session/modelCatalog', { args: {} })).default
  await guide(page).getByRole('button', { name: 'Start performance', exact: true }).click()
  await expect(page.locator('[data-conversation-content]')).toContainText('Welcome to the light.')
  expect(requests()).toHaveLength(0)
  const started = await call(page, 'papermoon-story/state', { playbookId: id })
  await call(page, 'papermoon/save', { playbookId: id, expectedSequence: started.sequence, operations: [{ kind: 'set-system-prompt', text: 'Later draft' }] })
  await send(page, 'What does the map show?')
  await expect(guide(page)).toHaveAttribute('data-story-completed', 'true')
  expect(requests()).toHaveLength(1)
  expect(requests()[0].reasoningEffort).toBe('high')
  expect(requests()[0].messages.map((message: { role: string }) => message.role)).toEqual(['system', 'user', 'assistant', 'user'])
  expect(requests()[0].messages[0].content[0].text).toBe(source)
  expect(requests()[0].messages[1].content[0].text).toBe('The harbor is quiet.')
  expect(requests()[0].messages[2].content[0].text).toBe('Welcome to the light.\nWhere did you find that map?')
  expect((await call(page, 'session/modelCatalog', { args: {} })).default).toEqual(defaults)
  await send(page, 'Later message')
  await expect.poll(() => requests().length).toBe(2)
  await expect(page.getByRole('button', { name: 'Stop generating', exact: true })).toBeHidden()
  const before = await call(page, 'papermoon-story/state', { playbookId: id })
  const review = await call(page, 'papermoon-story/review', { playbookId: id })
  expect(review.content.systemPrompt.text).toBe(source)
  expect(JSON.stringify(review.records)).not.toContain('Later message')
  await guide(page).getByRole('button', { name: 'Review chapter', exact: true }).click()
  await expect(guide(page)).toContainText('Chapter review')
  await guide(page).getByRole('button', { name: 'Return to current progress', exact: true }).click()
  expect((await call(page, 'papermoon-story/state', { playbookId: id })).sequence).toBe(before.sequence)
  expect((await call(page, 'papermoon/snapshot', { ref: { kind: 'draft', playbookId: id } })).content.systemPrompt.text).toBe('Later draft')
  await page.reload()
  await section(page, 5); await expect(guide(page)).toHaveAttribute('data-story-completed', 'true')
  await page.screenshot({ path: 'test-results/story-mode/first-character.png' })
  expect(errors).toEqual([])
})

test('collapsed reminders, keyboard hints, save isolation and empty openings preserve progress', async ({ page }) => {
  const id = await enter(page)
  await page.getByRole('button', { name: 'Collapse right sidebar', exact: true }).click()
  await expect(guide(page)).toHaveCount(0)
  const current = await call(page, 'papermoon-story/state', { playbookId: id })
  await call(page, 'papermoon-story/advance', { playbookId: id, section: 1, expectedSequence: current.sequence })
  await expect(page.getByRole('button', { name: 'Progress updated', exact: true })).toBeVisible()
  await expect(guide(page)).toHaveCount(0)
  await page.getByRole('button', { name: 'Progress updated', exact: true }).click()
  await section(page, 2)
  await expect(page.getByRole('button', { name: 'Progress updated', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  await guide(page).getByRole('button', { name: 'Show me where', exact: true }).click()
  await expect(guide(page)).toHaveCount(0)
  await expect(page.locator('.pm-guidance-hint')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  await page.getByRole('button', { name: 'Open right sidebar', exact: true }).click()
  await section(page, 2)
  await expect(page.locator('[data-story-unlock="opening"]')).toHaveCount(0)
  await expect(next(page)).toBeEnabled(); await next(page).click(); await section(page, 3)
  await expect(next(page)).toBeDisabled()
  const first = await call(page, 'papermoon-story/state', { playbookId: id })
  const second = await call(page, 'papermoon-story/create', { name: 'Second', projectId: first.playbook.projectId, storyline: 'fogbound-earthshine', language: 'en' })
  expect((await call(page, 'papermoon-story/state', { playbookId: second.id })).progress.section).toBe(1)
  expect((await call(page, 'papermoon/snapshot', { ref: { kind: 'draft', playbookId: id } })).content.opening.messages).toEqual([])
  const denied = await rpc(page, 'papermoon/save', { playbookId: second.id, expectedSequence: 0, operations: [{ kind: 'set-system-prompt', text: 'too early' }] })
  expect(denied.ok).toBe(false)
  expect(requests()).toHaveLength(0)
})

test('creation hint dismissal, trajectory examples and unlocked editor cues remain presentation state', async ({ page }) => {
  const id = await enter(page, true)
  const before = await call(page, 'papermoon-story/state', { playbookId: id })
  const examples = guide(page).locator('[data-prompt-trace]')
  await examples.scrollIntoViewIfNeeded()
  await expect(examples.locator('[data-prompt-role]')).toHaveText(['Input', 'Response'])
  const contents = await examples.locator('tbody tr td:last-child').allTextContents()
  await examples.locator('tbody tr').first().focus()
  await page.keyboard.press('ArrowDown')
  await expect(examples.locator('[data-prompt-content]')).toHaveText(contents[1]!)
  await expect(examples.locator('tbody tr').nth(1)).toBeFocused()
  await page.screenshot({ path: 'test-results/story-mode/trajectory-example.png' })
  expect((await call(page, 'papermoon-story/state', { playbookId: id })).sequence).toBe(before.sequence)
  expect(requests()).toHaveLength(0)
  await next(page).click(); await section(page, 2)
  const cue = page.locator('[data-story-unlock="opening"]')
  await expect(cue).toContainText('Opening editor')
  await page.reload(); await section(page, 2)
  await expect(cue).toContainText('Newly unlocked')
  const snapshot = await call(page, 'papermoon/snapshot', { ref: { kind: 'draft', playbookId: id } })
  expect(snapshot.content.opening.messages).toEqual([])
  await page.screenshot({ path: 'test-results/story-mode/unlocked-opening.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await examples.scrollIntoViewIfNeeded()
  await examples.locator('tbody tr').nth(1).click()
  await expect(examples.locator('[data-prompt-content]')).toContainText('The keeper opens the door a little.')
  const list = await examples.locator('table').boundingBox()
  const detail = await examples.locator('[data-prompt-content]').boundingBox()
  expect(detail!.y).toBeGreaterThan(list!.y + list!.height)
  await page.screenshot({ path: 'test-results/story-mode/trajectory-narrow.png' })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: 'Collapse right sidebar', exact: true }).click()
  await page.getByRole('button', { name: 'Story Mode', exact: true }).click()
  await page.locator('.pm-story-save').getByRole('button', { name: 'Continue', exact: true }).click()
  await section(page, 2)
  await expect(page.locator('.pm-guidance-hint')).toHaveCount(0)
})

test('Chinese guidance preserves role labels and layout in a narrow dark surface', async ({ browser }) => {
  const context = await browser.newContext({ locale: 'zh-CN', colorScheme: 'dark', viewport: { width: 390, height: 844 } })
  try {
    const page = await context.newPage()
    await page.goto(server.url)
    await page.getByRole('dialog', { name: '内测声明', exact: true }).getByRole('button', { name: '继续', exact: true }).click()
    // Native narrow navigation is hidden until its header control opens it.
    await page.getByRole('button', { name: '打开侧边栏', exact: true }).click()
    await page.getByRole('button', { name: '故事模式', exact: true }).click()
    await page.getByRole('textbox', { name: '存档名称', exact: true }).fill('守灯人')
    await page.getByRole('button', { name: '创建存档', exact: true }).click()
    await expect(guide(page)).toHaveCount(0)
    await expect(page.locator('.pm-guidance-hint')).toContainText('存档已创建。点击这里展开右侧栏，查看故事引导。')
    await page.locator('[data-sidebar-right-expand]').click()
    await section(page, 1)
    await guide(page).getByRole('button', { name: '继续', exact: true }).click()
    await section(page, 2)
    const examples = guide(page).locator('[data-prompt-trace]')
    await examples.scrollIntoViewIfNeeded()
    await expect(examples.locator('[data-prompt-role]')).toHaveText(['user', 'assistant'])
    await examples.locator('tbody tr').nth(1).click()
    await expect(examples.locator('[data-prompt-content]')).toContainText('守灯人')
    await page.screenshot({ path: 'test-results/story-mode/trajectory-zh-dark.png' })
  } finally { await context.close() }
})
